
#create database shop;
use shop;
CREATE TABLE user (
    name NVARCHAR(255) PRIMARY KEY,
    password VARCHAR(255)
)  DEFAULT CHARACTER SET UTF8MB4;
CREATE TABLE product (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name NVARCHAR(255) NOT NULL,
    price FLOAT NOT NULL,
    number INT UNSIGNED NOT NULL
)  DEFAULT CHARACTER SET UTF8MB4;
CREATE TABLE order_shop (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT REFERENCES user (name),
    product_id INT REFERENCES product (id),
    number INT UNSIGNED NOT NULL
)  DEFAULT CHARACTER SET UTF8MB4; 
CREATE TABLE cart (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL REFERENCES product (id),
    user_name VARCHAR(255) NOT NULL REFERENCES user (user_name),
    number INT UNSIGNED NOT NULL
)  DEFAULT CHARACTER SET UTF8MB4;